#!/bin/bash
#
# Generates top page for subpages that are created from NYK textfile.

cat ../templates/nyk.md.template > ../markdown/nyk.md

cd ../markdown/nyk
for file in *; do
	title=`basename $file .md`
	echo -e "[$title](nyk/$title.html)  \n" >> ../nyk.md
done
