#!/bin/bash
#
# Splits NYK textfile into multiple markdown files.

DIR_OUT='../markdown/nyk/'

if [[ ! -d "$DIR_OUT" ]]; then
	mkdir "$DIR_OUT"
fi

title=""
filename=""
atTitle="false"

SAVE_IFS="$IFS"
IFS=""
while read -r line; do
	# If line begins with two dots
	if [[ -n `echo "$line" | grep '^\.\.'` ]]; then
		atTitle="true"
		# Remove dots and spaces from line
		titleNewWord=`echo "$line" | tr -d '. '`
		# If line contains anything else then dots and spaces,
		# append it to the title
		if [[ -n "$titleNewWord" ]]; then
			title="$title""$titleNewWord "
		fi
	# If we are at the first line after the title
	elif [[ "$atTitle" == "true" ]]; then
		atTitle="false"
		# Remove last space from the title
		title=`echo "$title" | sed 's/ $//'`
		filename=`echo "$title" | tr [A-Z] [a-z] | tr ' ' '-'`.md
		# Append title to the new file named after title
		echo "$title" >> "$DIR_OUT$filename"
		# Append line of '='s to the same file
		echo "$title" | sed 's/./=/g' >> "$DIR_OUT$filename"
		title=""
	fi

	# If we are not processing title then just append line to the
	# file named after the last title,
	# if we havent encoutered the first title yet, do nothing
	if [[ "$atTitle" == "false" && -n "$filename" ]]; then
		echo "$line" >> "$DIR_OUT$filename"
	fi
done < ../../textfiles/NYK
IFS="$SAVE_IFS"
