#!/bin/bash
#
# Usage: install 
# For use on fresh debian install, that was installed with predefined values (preseeding), specified in preseed.cfg. It alows you to reset username/pasword, sets up git username/email, and basicaly takes care of little anoyances that come with default install.# The usernames/passwords and what specificaly gets set is specified by install.cfg configuration file.  

CONFIG_FILENAME='install.cfg'

# Greps parameters from config file, that belong to the passed group
getParameters() {
	cat "$CONFIG_FILENAME" | grep "^$1/" | sed 's/^[^\/]*\///'
}

# Greps for single parameter inside the group
# $1 group
# $1 parameter
getParam() {
	params=$(getParameters "$1")
	echo "$params" | grep "^$2 " | sed "s/^$2 //"
}

_git() {
	params=$(getParameters "git")
}

_system() {
	params=$(getParameters "system")
}

_ssh() {
	params=$(getParameters "ssh")
}

_vim() {
	params=$(getParameters "vim")
}

_awesome() {
	params=$(getParameters "awesome")
}

_lynx() {
	params=$(getParameters "lynx")
}

# Create directories in home
_directories() {
	param=$(getParam "directories" "create-new-in-home")
	mkdir $param
}

_cleanup() {
	params=$(getParameters "cleanup")
}


main() {
	_git
	_system
	_ssh
	_vim
	_awesome
	_lynx
	_directories
	_cleanup
}

main "$@"
